---
driver:
  name: docker
  use_sudo: false

provisioner:
  require_chef_omnibus: false
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  ansible_verbose: true

platforms:
  # Ubuntu 14.04 / Trusty
  - name: ubuntu-trusty
    driver_config:
      image: ubuntu:trusty
  # Ubuntu 12.04 / Precise
  - name: ubuntu-precise
    driver_config:
      image: ubuntu:precise
  - name: ubuntu-xenial
    driver_config:
      image: ubuntu:xenial

# Docs @ https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md
suites:
  # ROS Indigo supports Trusty and Saucy
  # http://wiki.ros.org/indigo/Installation/Ubuntu
  - name: indigo
    attributes:
      extra_vars:
        ros_release: indigo
    excludes:
      - ubuntu-precise

  # ROS Hyrdro supports Raring, Quantal, and Precise
  # http://wiki.ros.org/hydro/Installation/Ubuntu
  - name: hydro
    attributes:
      extra_vars:
        ros_release: hydro
    excludes:
      - ubuntu-trusty
      - ubuntu-xenial

  # ROS Groovy support Quantal, Precise, and Oneiric (No support for Oneiric here).
  # http://wiki.ros.org/groovy/Installation/Ubuntu
  - name: groovy
    attributes:
      extra_vars:
        ros_release: groovy
    excludes:
      - ubuntu-trusty
      - ubuntu-xenial

  
  - name: kinetic
    attributes:
      extra_vars:
        ros_release: kinetic
    excludes:
      - ubuntu-trusty
      - ubuntu-precise