- name: Install python
  include_tasks: ansible.yml

- name: Setup ket and repositories for ROS
  include_tasks: pre_install.yml

- name: Install ROS
  include_tasks: install_ros.yml

- name: After Installing ROS
  include_tasks: after_install.yml