---
- name: Add ROS repository apt-key
  become: yes
  apt_key:
    url: "{{ ros_apt_key }}"
    state: present

- name: Add ROS repository
  become: yes
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
