---
- name: Add ROS repository apt-key
  become: yes
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 421C365BD9FF1F717815A3895523BAEEB01FA116
    
- name: Add ROS repository
  become: yes
  apt_repository:
    repo: "deb {{ ros_apt_uri }} {{ ansible_lsb.codename }} main"
    state: present
